const { send } = require('express/lib/response')
const jsonwebtoken=require('jsonwebtoken')

function auth(req,res,next){
    const token=req.header('auth-token')
    if(!token){
        return res.status(401).send({message:'Access denied'})
    }
    try{
        const verified=jsonwebtoken.verify(token,process.env.TOKEN_SECRET)
        req.user=verified
        next()
    }catch(err){
        return res.status(401).send({message:'Invalid token'})
    }
}
// to use auth token, copy the token generated by login, go the postman go headers create new header called auth-token and paste the value there without ""
module.exports=auth